### PR TITLE
#15 issue solved

### PR DESCRIPTION
**Pull request by shudhanshu03**
So i have made a few changes and now the content of month section is aligned properly. @anubhavsingh16 .

### CODE REVIEW

**Comment by anubhavsingh16** [comment]
@shudhanshu03 before commit, please use git pull.

**Comment by shudhanshu03** [comment]
@anubhavsingh16 yeah actually i messed up , Please let me know the corrections i have made is correct or not ?

**Comment by anubhavsingh16** [comment]
Actually I just send all the files of the webpage to our new organisation.

 https://github.com/Catalyst-SMVD/OpneSourceEvents-Frontend
please have a look.

Because of me and my team members start a new organisation to work these kinds of projects please visit the new organisation and clone the repo and start your contribution.

thank you!
for any kind of query, please write on comment until we make a group.

**Comment by anubhavsingh16** [comment]
And don't worry tumhre commit is repo me dikhnge ok.😬

**Comment by shudhanshu03** [comment]
@anubhavsingh16 ohk bro , i will contribute bas btadio krna kya h .

**Comment by anubhavsingh16** [comment]
Okk aapne us repo ko clone keya jiski link maine send keya hai?

**Comment by shudhanshu03** [comment]
Ha bhai krlia maine

**Comment by shudhanshu03** [comment]
By the way maine piche repo me issue #15 solve krdia tha aap usse merge
krdo na agar aapko sahi lge toh

Content sab aligned krdia tha .

**Comment by anubhavsingh16** [comment]
Wo issue phale he solve ho gya hai agr mai tumhre PR merge krunga to project ek stage piche chla jayega.
So aap jo new org me repo hai isme issue bna skte ho and uske basis pr aap PR send kr do. Mai merge kr dunga. Ok

**Comment by shudhanshu03** [comment]
ohk i got it .

**Pull request closed without merging**
